// src/components/IncidentCard — the incident card family (compact + full) and its pure logic.
export { IncidentCard, type IncidentCardProps, type IncidentCardVariant } from './IncidentCard.tsx';
export { SeverityGlyph, type SeverityGlyphProps, type GlyphSize } from './SeverityGlyph.tsx';
export { useIncidentContext, renderTemplate, type IncidentContextValue } from './context.tsx';
export {
  CAUGHT_LIVE_WINDOW_MS,
  CATCH_UP_NOTE,
  DEMO_PROFILE_NOTE,
  causeInfo,
  caughtStartMs,
  caughtState,
  commitEffectiveMs,
  commitWhen,
  deliveryLine,
  deliveryLines,
  endpointName,
  expectsDelivery,
  formatClockTime,
  formatReading,
  hasNote,
  impactFigures,
  impactText,
  impactWording,
  incidentLabel,
  incidentMeasure,
  incidentTitle,
  incidentTone,
  isBellEndpoint,
  isDelivered,
  latestDeliveries,
  ledgerHref,
  mutedMinutesLeft,
  objectKindWord,
  openSeconds,
  primaryDelivery,
  rankDeliveries,
  recoveryDeliveries,
  recoveryMeasure,
  recoveryText,
  shortHash,
  type CauseInfo,
  type CauseKind,
  type CaughtState,
  type DeliveryLine,
  type DeliveryTone,
  type IncidentMeasure,
  type RecoveryMeasure,
  type Tone,
} from './model.ts';
