// src/components/PriceTable — the Prices table and its pure model (SPEC 5, 6, 8).
export { PriceTable, type PriceTableProps } from './PriceTable.tsx';
export { PresetInfoButton, type PresetInfoButtonProps } from './PresetInfoButton.tsx';
export { PendingList, ReceiptTotals, RowReceiptLine } from './LiveReceipt.tsx';
export { destinationVolumes, draftReceipt, pendingChanges, type DraftReceipt, type PendingChange, type RowReceipt } from './receiptModel.ts';
export {
  CUSTOM_PRESET,
  applyPreset,
  buildRows,
  collectChanges,
  counterfactualKey,
  counterfactualOptions,
  destinationMeta,
  draftToEntry,
  editPrice,
  fillSuggested,
  initialDraft,
  initialDrafts,
  isCustomDraft,
  isDirty,
  isListedOutput,
  listDestinations,
  parseCounterfactualKey,
  presetDollars,
  presetInfo,
  presetNoteLine,
  presetOptionGroups,
  presetOptions,
  pricePlaceholder,
  rowCounts,
  rowNoteLine,
  suggestableCount,
  usdPerGb,
  validateDraft,
  type Destination,
  type DraftPreset,
  type Option,
  type PriceChanges,
  type PriceDraft,
  type PriceFieldErrors,
  type PresetInfo,
  type PresetOption,
  type PresetOptionGroup,
  type PriceRow,
} from './model.ts';
