// src/tour/fixture.ts — the bundled tour fixture (demo/sample/tour.json, generated by testdata/tour.ts).
// Imported statically: the sample workspace ships inside the app bundle (in the lazily loaded chunk of
// whichever view starts the tour) and never costs a network or Cribl call. Both builds carry it — the
// release build's first run offers the tour, and Story mode plays it.

import raw from '../../demo/sample/tour.json';
import type { TourFixture } from './types.ts';

export const TOUR_FIXTURE: TourFixture = raw as unknown as TourFixture;
