// src/story/doc.ts — the bundled story document (demo/sample/story.json, generated by scripts/story.ts)
// and `beatAt(tSeconds)`: what is on screen at any second of the loop. The Playwright video capture
// calls beatAt to cut scenes and check captions; the Story view asks the same function every frame.
//
// Both builds carry story.json (the tour fixture's story, SAMPLE DATA band on). The demo build's
// story-live.json (from a recorded replay.json) does not exist yet; see src/views/Story/source.ts.

import type { StoryDoc } from '../../core/types.ts';
import raw from '../../demo/sample/story.json';
import { tLines } from '../copy/en.ts';
import { positionAt, type StoryPosition } from './timeline.ts';

/**
 * D54: the closing ask is this build's own `story.captions.ask`. scripts/story.ts writes every document in plain
 * Node, where the build flag is unset, so the files carry the release's join line; the demo build swaps its vote
 * ask back in here. Both asks are two lines, so the caption windows and the ask's callout keep their times. In the
 * release build the swap is a no-op, and the release bundle never holds the vote line.
 */
export function withBuildAsk(doc: StoryDoc): StoryDoc {
  const ask = tLines('story.captions.ask');
  if (!doc.beats.some((b) => b.id === 'ask')) return doc;
  return { ...doc, beats: doc.beats.map((b) => (b.id === 'ask' ? { ...b, caption: ask } : b)) };
}

export const STORY_DOC: StoryDoc = withBuildAsk(raw as unknown as StoryDoc);

/** Which beat, caption line and callouts are on screen `tSeconds` into Story mode (it loops). */
export function beatAt(tSeconds: number, doc: StoryDoc = STORY_DOC): StoryPosition {
  return positionAt(doc, tSeconds);
}
